#!/bin/sh
# Environmental setup
umask 022
export PATH="/bin:/usr/bin:/sbin:/usr/sbin"

# Color definitions
NORMAL="\\033[0;39m"
GREEN="\\033[1;32m"
YELLOW="\\033[1;33m"
RED="\\033[1;31m"
CYAN="\\033[1;36m"
BLUE="\\033[1;34m"

msg_red()
{
	echo -e "${RED}${1}${NORMAL}"
}
msg_green()
{
	echo -e "${GREEN}${1}${NORMAL}"
}

msg_blue()
{
	echo -e "${BLUE}${1}${NORMAL}"
}
msg_yellow()
{
	echo -e "${YELLOW}${1}${NORMAL}"
}
msg_cyan()
{
	echo -e "${CYAN}${1}${NORMAL}"
}


